# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mak.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QHBoxLayout, QVBoxLayout, QGridLayout, QSizePolicy


class Ui_Form(QMainWindow):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.list_order = []
        self.grid = QGridLayout(Form)
        self.checkox_layout = QVBoxLayout(Form)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.label = QtWidgets.QLabel(Form)
        self.lineEdit = QtWidgets.QPlainTextEdit(Form)

        # add widgets
        self.grid.addWidget(self.label, 1, 0, 1, 2)
        self.grid.addWidget(self.checkBox)
        self.grid.addWidget(self.checkBox_2)
        self.grid.addWidget(self.checkBox_3)
        self.grid.addWidget(self.checkBox_4)
        self.grid.addWidget(self.pushButton, 5, 0, 2, 1)
        self.checkBox.clicked.connect(lambda: self.add_list(self.checkBox))
        self.checkBox_2.clicked.connect(lambda: self.add_list(self.checkBox_2))
        self.checkBox_3.clicked.connect(lambda: self.add_list(self.checkBox_3))
        self.checkBox_4.clicked.connect(lambda: self.add_list(self.checkBox_4))

        self.grid.addWidget(self.lineEdit, 5, 1, 2, 1)
        self.lineEdit.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        self.pushButton.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.pushButton.clicked.connect(self.add_products)
        self.setLayout(self.grid)

    def add_list(self, two):
        if two.isChecked():
            self.list_order.append(two.text())
        else:
            self.list_order.remove(two.text())

    def add_products(self):
        self.lineEdit.clear()
        string = 'Ваш заказ:\n\n'
        for i in self.list_order:
            string += i + '\n'
        self.lineEdit.setPlainText(string)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 610)
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setDisabled(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("first.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3.setAutoFillBackground(False)
        self.checkBox_3.setAutoRepeat(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "Чизбургег"))
        self.checkBox_2.setText(_translate("Form", "Гамбургер"))
        self.checkBox_3.setText(_translate("Form", "Кока-кола"))
        self.checkBox_4.setText(_translate("Form", "Наггетсы"))
        self.pushButton.setText(_translate("Form", "Заказать"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
